import iconImg from '../assets/images/site/icon.svg';
import ogDefaultImg from '../assets/images/site/og-default.png';
import type { GiscusConfig, NavigationConfig, SiteConfig } from '@tsche/astro-blog-theme/config';

/**
 * Global site configuration.
 * Edit values here to rebrand the site. All values are typed and consumed
 * across layouts, components, RSS, sitemap, and SEO.
 */

// Export imported site images for use in components
export const SITE_IMAGES = {
  avatar: iconImg,
  favicon: iconImg,
  ogDefault: ogDefaultImg,
} as const;

/**
 * GitHub coordinates, configurable by the deployment environment.
 */
const GITHUB_HANDLE = 'tsche';
const GITHUB_REPO = 'cpptips';

/**
 * Public GitHub coordinates of the deployed source. Useful for custom links
 * and integrations that need a repository URL.
 */
export const REPO = {
  handle: GITHUB_HANDLE,
  name: GITHUB_REPO,
  url: GITHUB_HANDLE ? `https://github.com/${GITHUB_HANDLE}/${GITHUB_REPO}` : 'https://github.com',
} as const;

export const SITE: SiteConfig = {
  // ==========================================
  // ✅ SAFE TO EDIT (Content & Presentation)
  // ==========================================

  /** Default site title used as homepage <title> and meta. */
  title: 'C++ Tips',
  /** Site tagline / description. */
  description:
    'C++ tips, technical articles, and updates about reflection, compilers, template malarkey, and useful cursed code.',
  /** Content types published by this site. Keys select theme styling/layout. */
  contentTypes: {
    tips: {
      label: 'Tips',
      singularLabel: 'Tip',
      description: "Tips and tricks that didn't fill a proper long-form article",
      preview: 'excerpt',
      landingPageLimit: 4,
      postsPerPage: 8,
    },
    articles: {
      label: 'Articles',
      singularLabel: 'Article',
      description: 'Long-form C++ articles',
      preview: 'description',
      landingPageLimit: 5,
      postsPerPage: 8,
    },
    updates: {
      label: 'Updates',
      singularLabel: 'Update',
      description: "Updates on cool stuff that's happening",
      preview: 'excerpt',
      landingPageLimit: 5,
      postsPerPage: 8,
    },
  },
  /** Author/handle shown in footer + meta. */
  author: {
    name: 'Matthias Wippich',
    url: GITHUB_HANDLE ? `https://github.com/${GITHUB_HANDLE}` : undefined,
    avatar: iconImg,
    bio: 'Independent field notes from the C++ community.',
  },
  contentLicense: {
    label: 'CC BY 4.0',
    url: 'https://creativecommons.org/licenses/by/4.0/',
  },
  /** Default OG image. */
  defaultOgImage: ogDefaultImg.src,
  /** Number of posts per page on listings. */
  postsPerPage: 8,
  /** Display ISO 8601 dates when true, otherwise readable English dates. */
  isoDates: false,
  /** Site-wide default for whether posts should display their featured image. */
  showFeaturedImages: true,
  /** Wrap the article body of posts and pages in a bordered, card-like container. */
  boxedArticles: false,
  /** Allow listing cards to grow when title/description content is longer. */
  dynamicPostCardHeight: false,
  /** Tags that are implicit for this site and add no value on overview cards. */
  overview: {
    hiddenTags: ['C++'],
  },
  /** Automatically generate Open Graph images for posts that don't have a `heroImage`. */
  autoOgImage: true,
  analytics: {
    umami: {
      websiteId: '0d7d7a2d-8fdf-49fb-b9fb-c9b0637cc16e',
      scriptUrl: 'https://analytics.cpp.social/script.js',
      domains: ['cpp.tips'],
      respectDoNotTrack: true,
    },
  },
  // ==========================================
  // ❗ CAN BREAK THINGS (EDIT WITH CAUTION)
  // ==========================================

  /** Public URL of the deployed site, no trailing slash. Breaks SEO/RSS if incorrect. */
  url: 'https://cpp.tips',
};

export const NAV = {
  top: [
    { label: 'Tips', href: '/tips' },
    { label: 'Articles', href: '/articles' },
    { label: 'Updates', href: '/updates' },
    { label: 'About', href: '/about' },
  ],
  footer: [
    { label: 'About', href: '/about' },
    { label: 'Archive', href: '/archives' },
    { label: 'Tags', href: '/tags' },
    { label: 'Categories', href: '/categories' },
    { label: 'RSS', href: '/rss.xml', icon: 'lucide:rss' },
    { label: 'Sitemap', href: '/sitemap.xml' },
  ],
} as const satisfies NavigationConfig;

/**
 * Giscus comments. Set `enabled: false` to globally disable. Individual
 * posts may opt out via frontmatter `comments: false`.
 *
 * Generate values at https://giscus.app and set them here.
 */
export const GISCUS: GiscusConfig = {
  enabled: false,
  repo: '',
  repoId: '',
  category: 'Announcements',
  categoryId: '',
  mapping: 'pathname',
  strict: '0',
  emitMetadata: '0',
  inputPosition: 'bottom',
  loading: 'lazy',
};

/**
 * Pagefind runtime settings. The index itself is generated by `bun run pagefind`
 * after `astro build` and written to `dist/_pagefind/`.
 */
export const PAGEFIND = {
  /** Public path where the Pagefind bundle is served. */
  bundlePath: '/_pagefind/',
  /** Number of results to render at once. */
  pageSize: 10,
} as const;
